services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-cms-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
